#AutomateTheBoringStuff
print("HelloWorld")
print("")
print("CHAPTER (1)")
print("")
print("Below you will see examples of Python Expressions")
print("** = Exponent (2**3 = 8)")
print("% = Modulus/remainder (22 % 8 = 6)")
print("// = Integer division/floor quotient (22 // 8 = 2)")
print("/ = Division (22 / 8 = 2.75)")
print("* = Multiplication (3 * 5 = 15)")
print("- = Subtraction(5 - 2 = 3)")
print("+ = Addition(2 + 2 = 4)")
print("")
print('Order of operations is called "Precedence" and goes as follows from left to right:')
print("**,*,/,//,%, +,-")
print("You may use parenthesis to override read order.")